name: person_event_atlas
description: 本地优先的人物事件档案。
publish_to: none
version: 0.1.18+41

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  country_state_city_pro: ^0.0.6
  file_selector: ^1.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.7.4
  sqlite3_flutter_libs: ^0.5.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - THIRD_PARTY_NOTICES.md
